package com.example.entity;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_time
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    private Date roleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_person
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    private String rolePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_remark
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    private String roleRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.dept_id
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_time
     *
     * @return the value of role.role_time
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public Date getRoleTime() {
        return roleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_time
     *
     * @param roleTime the value for role.role_time
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public void setRoleTime(Date roleTime) {
        this.roleTime = roleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_person
     *
     * @return the value of role.role_person
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public String getRolePerson() {
        return rolePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_person
     *
     * @param rolePerson the value for role.role_person
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public void setRolePerson(String rolePerson) {
        this.rolePerson = rolePerson == null ? null : rolePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_remark
     *
     * @return the value of role.role_remark
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public String getRoleRemark() {
        return roleRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_remark
     *
     * @param roleRemark the value for role.role_remark
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public void setRoleRemark(String roleRemark) {
        this.roleRemark = roleRemark == null ? null : roleRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.dept_id
     *
     * @return the value of role.dept_id
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.dept_id
     *
     * @param deptId the value for role.dept_id
     *
     * @mbg.generated Sat Dec 15 14:40:57 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}